### ISSUE TITLE
Long range shooting doesn't work

### ISSUE THREAD

**Issue by willrnt05** [camgrodgers/senior-fps#31] opened 2021-01-23 19:34 UTC
Think it probably has to do with the Ray cast thing from the gun.  Honestly idk

**Comment by camgrodgers** [comment] 2021-01-23 19:41
After testing, I think this is caused by the raycast colliding with the enemy's VisionCone collision area before it reaches the enemy's hitbox. The fix for this is likely to change the collision mask bits on several things.

**Closed** 2021-01-23 23:36 UTC
